#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

# https://wiki.archlinux.org/title/Bluetooth
# 
# Pair a device with bluetoothctl:
# > bluetoothctl
# > power on
# > agent on
# > default-agent
# > scan on
# > pair XX:XX
# > trust XX:XX
# > connect XX:XX
# > exit
#
# Fix poor quality:
# 
# - pactl list cards short
# - pactl set-card-profile <bluetooth_card> ad2p_sink
# - pulseaudio -k
# - sudo systemctl restart bluetooth.service

if __is_arch; then

    # Setup bluetooth service
    if ! systemctl is-active -q bluetooth.service; then
	__pacman_install bluez bluez-utils
	# TODO: remove prompt
	systemctl start bluetooth.service
	systemctl enable bluetooth.service
    fi

    # Setup audio
    if ! systemctl is-active --user pulseaudio.service; then
	__pacman_install pulseaudio pulseaudio-bluetooth
	systemctl --user restart pulseaudio
    fi

fi

