#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

# https://wiki.archlinux.org/title/Bluetooth
# 
# Pair a device with bluetoothctl:
# > bluetoothctl
# > power on
# > agent on
# > default-agent
# > scan on
# > pair XX:XX
# > trust XX:XX
# > connect XX:XX
# > exit
#
# Fix poor quality:
# 
# - pactl list cards short
# - pactl set-card-profile <bluetooth_card> ad2p_sink
# - pulseaudio -k
# - sudo systemctl restart bluetooth.service
#
# add file "/etc/NetworkManager/conf.d/wifi-powersave-off.conf"
# [connection]
# wifi.powersave = 2
#
# sudo systemctl restart NetworkManager
# reboot

echo "skip"
