#!/bin/bash

set -euo pipefail
IFS=$'\n\t'


if cat /etc/os-release | grep -q "ID=ubuntu"; then

    # Core packages
    sudo apt install -y git vim less unzip usbutils xclip

elif cat /etc/os-release | grep -q "ID=arch"; then

    # Core packages
    sudo pacman -Syu linux-firmware git vim less unzip usbutils xclip --noconfirm

    # Install yay
    sudo pacman -S --needed base-devel git --noconfirm
    git clone https://aur.archlinux.org/yay.git
    pushd yay
    makepkg -si --noconfirm
    popd
    rm -rf yay

fi

