#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

USERNAME=$(whoami)

# Install Docker dependencies
sudo apt install -y curl ca-certificates

# Download Docker GPG Key
if [[ ! -f "/etc/apt/keyrings/docker.asc" ]]; then
    install -m 0755 -d /etc/apt/keyrings
    sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    sudo chmod a+r /etc/apt/keyrings/docker.asc
fi

# Add the repository to apt sources and update
if [[ ! -f "/etc/apt/sources.list.d/docker.list" ]]; then
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt update -y
fi

# Install Docker Engine
sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# Add user to docker group

if ! getent group "docker" > /dev/null 2>&1; then
    sudo groupadd docker
    sudo usermod -aG docker $USERNAME
    newgrp docker
fi
