#!/bin/bash

set -euo pipefail
IFS=$'\n\t'


# Install dotfiles dependencies
if cat /etc/os-release | grep -q "ID=ubuntu"; then
	sudo apt install -y stow fontconfig make yarn
elif cat /etc/os-release | grep -q "ID=arch"; then
	sudo pacman -Syu stow fontconfig make yarn --noconfirm
fi

# Make dotfiles
rm "$HOME/.zshrc" || true
pushd "$HOME/dotfiles"
make stow
make setup
popd

# Reload fonts
fc-cache -f -v

# Create directories
mkdir -p "$HOME/personal" "$HOME/work"

# Source .zshrc
if command -v zsh &> /dev/null; then
    yes | zsh "$HOME/.zshrc" || if [[ $? -eq 141 ]]; then true; else false; fi
fi

# Install Neovim plugins
command -v "$HOME/.local/bin/nvim" &> /dev/null && "$HOME/.local/bin/nvim" --headless "+Lazy! sync" +qa
