#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

# Clone fzf
__git_clone "https://github.com/junegunn/fzf.git" "$HOME/.fzf"

# Install fzf
yes | "$HOME/.fzf/install" || if [[ $? -eq 141 ]]; then true; else false; fi
