#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

if cat /etc/os-release | grep -q "ID=ubuntu"; then

    sudo apt install -y gimp

elif cat /etc/os-release | grep -q "ID=arch"; then

    sudo pacman -Syu gimp --noconfirm

fi
