#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

# Install packages using pacman if not already installed
# Usage: __pacman_install package1 package2 ...
__pacman_install() {
    for package in "$@"; do
        if ! sudo pacman -Q "$package"; then
            sudo pacman -Syu "$package" --noconfirm
        fi
    done
}

# Return true if using Arch
__is_arch() {
    if grep -q "ID=arch" /etc/os-release; then
        return 0
    else
        return 1
    fi
}

# Return true if using Ubuntu
__is_ubuntu() {
    if grep -q "ID=ubuntu" /etc/os-release; then
        return 0
    else
        return 1
    fi
}

# Clone repo to location if doesn't exist
# Usage: __git_clone repo path
__git_clone() {
    repo="$1"
    dest="$2"
    git -C "$dest" pull || git clone "$repo" "$dest"
}
