#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

# Install i3 and dependencies
if __is_ubuntu; then
    sudo apt install -y i3 picom feh rofi dunst polybar acpi brightnessctl net-tools lm-sensors
elif __is_arch; then
    __pacman_install i3 picom feh rofi dunst polybar acpi brightnessctl net-tools xorg-xrandr xorg-xinput
fi

# Configure brightnessctl
sudo chmod +s "$(which brightnessctl)"
