#!/bin/bash

set -euo pipefail
IFS=$'\n\t'



# Install zsh
if cat /etc/os-release | grep -q "ID=ubuntu"; then
    sudo apt install -y i3 picom feh rofi dunst polybar acpi brightnessctl net-tools lm-sensors
elif cat /etc/os-release | grep -q "ID=arch"; then
    sudo pacman -Syu i3 picom feh rofi dunst polybar acpi brightnessctl net-tools xorg-xrandr xorg-xinput --noconfirm
fi

# Install i3 and dependencies

# Configure brightnessctl
sudo chmod +s "$(which brightnessctl)"
