#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

# get latest release link
# curl -Ls -o /dev/null -w %{url_effective} github.com/neovim/neovim/releases/latest

NEOVIM_VERSION="0.11.2"
NEOVIM_RELEASE_URL="https://github.com/neovim/neovim/releases/download/v${NEOVIM_VERSION}/nvim-linux-x86_64.appimage"


# Install Neovim dependencies
if __is_ubuntu; then
    sudo apt install -y ripgrep npm curl cargo python3-venv
elif __is_arch; then
    __pacman_install ripgrep npm curl cargo python-virtualenv
fi

# Install Neovim AppImage
if [[ ! -f $HOME/.local/bin/nvim ]]; then
    curl -L "$NEOVIM_RELEASE_URL" -o "$HOME/nvim.appimage"
    chmod +x "$HOME/nvim.appimage"
    pushd "$HOME" > /dev/null
    ./nvim.appimage --appimage-extract
    popd > /dev/null
    rm -rf "$HOME/.nvim" || true
    sudo mv "$HOME/squashfs-root" "$HOME/.nvim"
    mkdir -p "$HOME/.local/bin/"
    ln -s "$HOME/.nvim/AppRun" "$HOME/.local/bin/nvim"
    rm "$HOME/nvim.appimage"
fi
