#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

if __is_ubuntu; then

    if ! command -v zsh &>/dev/null; then
        curl -fsSL https://opencode.ai/install | bash
    fi

elif __is_arch; then

    __pacman_install opencode

fi
