#!/bin/bash

set -euo pipefail
IFS=$'\n\t'


if __is_ubuntu; then

    # Install python packages
    sudo apt install -y python3 python3-pip

fi


# Install uv
if ! command -v uv &> /dev/null; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
fi

