#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

if cat /etc/os-release | grep -q "ID=ubuntu"; then

    sudo snap install spotify

elif cat /etc/os-release | grep -q "ID=arch"; then

	sudo pacman -Syu spotify-launcher --noconfirm

fi

