#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

# Install tmux
if __is_ubuntu; then
	sudo apt install -y tmux
elif __is_arch; then
	__pacman_install tmux
fi

# Install tpm
repo="https://github.com/tmux-plugins/tpm"
dest="$HOME/.tmux/plugins/tpm"
git -C "$dest" pull || git clone "$repo" "$dest"
