#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

# Finish pending upgrades
sudo dpkg --configure -a

# Disable auto upgrade
sudo apt remove -y unattended-upgrade || true

# Update packages
sudo apt update -y
sudo apt upgrade -y
