#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

if cat /etc/os-release | grep -q "ID=ubuntu"; then

	# Finish pending upgrades
	sudo dpkg --configure -a

	# Disable auto upgrade
	sudo apt remove -y unattended-upgrade || true

	# Update packages
	sudo apt update -y
	sudo apt upgrade -y


elif cat /etc/os-release | grep -q "ID=arch"; then
	sudo pacman -Syu --noconfirm
fi
