#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

if __is_ubuntu; then

    sudo apt install -y virtualbox

elif __is_arch; then
    # https://wiki.archlinux.org/title/VirtualBox
    __pacman_install virtualbox-host-modules-arch virtualbox 

    echo "Reboot and run \"sudo modprobe vboxdrv\" for Virtualbox to finish installing."

fi

