#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

USERNAME=$(whoami)

# Install zsh
sudo apt install -y zsh

# Install ohmyzsh
[ -d "$HOME/.oh-my-zsh" ] || sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Make zsh default
sudo chsh -s $(which zsh) $USERNAME

# Install zsh-autosuggestions
repo="https://github.com/zsh-users/zsh-autosuggestions.git"
dest="$HOME/.oh-my-zsh/plugins/zsh-autosuggestions"
git -C "$dest" pull || git clone "$repo" "$dest"

# Install zsh-syntax-highlighting
repo="https://github.com/zsh-users/zsh-syntax-highlighting.git"
dest="$HOME/.oh-my-zsh/plugins/zsh-syntax-highlighting"
git -C "$dest" pull || git clone "$repo" "$dest"
