#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

USERNAME=$(whoami)

# Install zsh
if __is_ubuntu; then
	sudo apt install -y zsh
elif __is_arch; then
	__pacman_install zsh
fi

# Install ohmyzsh
[ -d "$HOME/.oh-my-zsh" ] || sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

# Make zsh default
if __is_ubuntu; then
	yes | sudo chsh -s $(which zsh) $USERNAME || if [[ $? -eq 141 ]]; then true; else false; fi
elif __is_arch; then
	chsh -s $(which zsh) $USERNAME
fi

# Install zsh-autosuggestions
repo="https://github.com/zsh-users/zsh-autosuggestions.git"
dest="$HOME/.oh-my-zsh/plugins/zsh-autosuggestions"
git -C "$dest" pull || git clone "$repo" "$dest"

# Install zsh-syntax-highlighting
repo="https://github.com/zsh-users/zsh-syntax-highlighting.git"
dest="$HOME/.oh-my-zsh/plugins/zsh-syntax-highlighting"
git -C "$dest" pull || git clone "$repo" "$dest"
