#!/usr/bin/env bash

os=$(uname)
KITTYPATH="$HOME"/dotfiles/.config/kitty

# Linux
if [[ $os == "Linux" ]]; then
    echo "Configuring Kitty for Ubuntu"
    ln -sf "$KITTYPATH"/ubuntu.conf "$KITTYPATH"/kitty.conf

    if [[ -n $(command -v conda) ]]; then
        echo "Configuring Conda for Ubuntu"
        conda init zsh 1> /dev/null
    fi

# Mac
elif [[ $os == "Darwin" ]]; then
    echo "Configuring Kitty for macOS"
    ln -sf "$KITTYPATH"/macos.conf "$KITTYPATH"/kitty.conf

    if [[ -n $(command -v /opt/anaconda3/bin/conda) ]]; then
        echo "Configuring Conda for macOS"
        /opt/anaconda3/bin/conda init zsh 1> /dev/null
    fi

else
    echo "Unsupported OS: ${os}"
fi

# TODO: use makefile and move this to .local/bin
