- name: Install Packages
  become: true
  ansible.builtin.apt:
    name:
      - unzip
      - curl
      - ca-certificates
      - make
    state: present
  tags:
    - always

- name: Install Utils
  become: true
  ansible.builtin.apt:
    name:
      - xclip
    state: present
  tags:
    - always

- name: Disable Unattended Upgrades
  become: true
  ansible.builtin.apt:
    name:
      - unattended-upgrades
    state: absent
  tags:
    - always
