- name: Configure git defaults # noqa command-instead-of-module
  ansible.builtin.shell: |
    git config --global user.name "Joseph Bednar"
    git config --global push.autoSetupRemote true
    git config --global credential.helper store
    git config --global fetch.prune true
    git config --global core.editor nvim
  changed_when: true
  tags:
    - git
