- name: Install nvim dependencies
  become: true
  ansible.builtin.apt:
    name:
      - ripgrep
      - npm
      - curl
      - cargo
      - python3-venv
    state: present
  tags:
    - nvim

- name: Check if nvim in bin
  become: true
  ansible.builtin.stat:
    path: "/usr/bin/nvim"
  register: nvim_status
  tags:
    - nvim

- name: Download Nvim
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/download/v0.10.4/nvim-linux-x86_64.appimage"
    dest: "{{ home_dir }}/nvim.appimage"
    mode: "u+x"
  when: not nvim_status.stat.exists
  changed_when: not nvim_status.stat.exists
  tags:
    - nvim

- name: Install nvim
  become: true
  ansible.builtin.shell: |
    cd {{ home_dir }}
    ./nvim.appimage --appimage-extract
    mv {{ home_dir }}/squashfs-root {{ home_dir }}/.nvim
    rm /usr/bin/nvim
    ln -s {{ home_dir }}/.nvim/AppRun /usr/bin/nvim
    rm {{ home_dir }}/nvim.appimage
  when: not nvim_status.stat.exists
  changed_when: not nvim_status.stat.exists
  tags:
    - nvim
