- name: Install tmux
  become: true
  ansible.builtin.apt:
    name:
      - tmux
    state: present
  tags:
    - tmux

- name: Install Tmux Plugin Manager
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "~/.tmux/plugins/tpm"
    clone: true
    update: true
  tags:
    - tmux
