- name: Install Zsh
  become: true
  ansible.builtin.apt:
    name:
      - zsh
    state: present
  tags:
    - zsh

- name: Check if oh-my-zsh installed
  ansible.builtin.stat:
    path: "{{ home_dir }}/.oh-my-zsh"
  register: ohmyzsh_status
  tags:
    - zsh

- name: Install ohmyzsh
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ home_dir }}/.oh-my-zsh"
  when: not ohmyzsh_status.stat.exists
  tags:
    - zsh

- name: Set zsh as default shell
  become: true
  ansible.builtin.shell: chsh -s $(which zsh) {{ username }}
  changed_when: true
  tags:
    - zsh

- name: Install zsh-autosuggestions # noqa latest
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
    clone: true
    update: true
  tags:
    - zsh

- name: Install zsh-syntax-highlighting # noqa latest
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
    clone: true
    update: true
  tags:
    - zsh
