#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

pushd "$HOME/dotfiles/install/jobs"
source ./core
source ./update
source ./zsh
source ./fzf
source ./tmux
source ./nvim
source ./node
source ./git
source ./dotfiles
popd
