#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

pushd "$HOME/dotfiles/install/jobs"
bash ./update
bash ./zsh
bash ./fzf
bash ./tmux
bash ./nvim
bash ./node
bash ./docker
bash ./python
bash ./apps
bash ./i3
bash ./git
bash ./k8s
bash ./keyboard
bash ./dotfiles
popd
