#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

pushd "$HOME/dotfiles/install/jobs"
source ./update
source ./zsh
source ./fzf
source ./tmux
source ./nvim
source ./node
source ./docker
source ./python
source ./gimp
source ./kitty
source ./spotify
source ./i3
source ./git
source ./k8s
source ./keyboard
source ./dotfiles
popd
