#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

pushd "$HOME/dotfiles/install/jobs"
source ./core
source ./update
source ./bluetooth
source ./zsh
source ./fzf
source ./tmux
source ./nvim
source ./node
source ./docker
source ./python
source ./gimp
source ./kitty
source ./spotify
source ./virtualbox
source ./i3
source ./git
source ./k8s
source ./firefox
source ./redshift
source ./vpn
source ./gtk
source ./dolphin
source ./dotfiles
popd


