#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

bash $HOME/dotfiles/install/jobs/update
bash $HOME/dotfiles/install/jobs/zsh
bash $HOME/dotfiles/install/jobs/fzf
bash $HOME/dotfiles/install/jobs/tmux
bash $HOME/dotfiles/install/jobs/nvim
bash $HOME/dotfiles/install/jobs/node
bash $HOME/dotfiles/install/jobs/docker
bash $HOME/dotfiles/install/jobs/python
bash $HOME/dotfiles/install/jobs/apps
bash $HOME/dotfiles/install/jobs/i3
bash $HOME/dotfiles/install/jobs/git
bash $HOME/dotfiles/install/jobs/k8s
bash $HOME/dotfiles/install/jobs/dotfiles
