require('nvim.set')
require('nvim.plugins')
require('nvim.keymaps')
require('nvim.theme')
require('nvim.lualine')
require('nvim.treesitter')
require('nvim.lsp')
require('nvim.null-ls')
require('nvim.harpoon')

