name: CI

on: [push, pull_request]

jobs:
    format:
        name: Check formatting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: date +%W > weekly

            - name: Restore cache
              id: cache
              uses: actions/cache@v4
              with:
                path: |
                  ~/.cargo/bin
                key: ${{ runner.os }}-cargo-${{ hashFiles('weekly') }}

            - name: Install stylua
              if: steps.cache.outputs.cache-hit != 'true'
              run: cargo install stylua

            - name: Check lua format
              run: stylua --check .config/nvim/lua/ #--config-path=.stylua.toml

    docker-build:
        name: Build Docker image
        runs-on: ubuntu-latest
        steps:
            - name: Log in to GitHub Container Registry
              run: echo "${{ secrets.CI }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - uses: actions/checkout@v4
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag dev-env:${{ github.run_id }}

            - name: Push the image
              if: github.ref == 'refs/heads/main'
              run: |
                  docker tag dev-env:${{ github.run_id }} ghcr.io/${{ github.repository_owner }}/dev-env:latest
                  docker push ghcr.io/${{ github.repository_owner }}/dev-env:latest
