name: CI

on: [push, pull_request]

jobs:
    format:
        name: Check formatting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: date +%W > weekly

            - name: Restore cache
              id: cache
              uses: actions/cache@v4
              with:
                path: |
                  ~/.cargo/bin
                key: ${{ runner.os }}-cargo-${{ hashFiles('weekly') }}

            - name: Install stylua
              if: steps.cache.outputs.cache-hit != 'true'
              run: cargo install stylua

            - name: Check lua format
              run: stylua --check .config/nvim/lua/ #--config-path=.stylua.toml

